<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '16:9' => '16:9',
    '180°' => '180°',
    '1:1' => '1:1',
    '4:3' => '4:3',
    '90° Clockwise' => '90° im UZS',
    '90° Counter Clockwise' => '90° gegen UZS',
    'A file with the name "{name}" already exists.' => 'Eine Datei mit dem Namen "{name}" existiert bereits.',
    'All devices' => 'Alle Geräte',
    'Alt text' => 'Alt Text',
    'Aspect ratio' => 'Seitenverhältnis',
    'Assets' => 'Assets',
    'Change folder order' => 'Reihenfolge der Order ändern',
    'Clear Selection' => 'Selektion aufheben',
    'Create New Folder' => 'Neuen Ordner erstellen',
    'Create new folders' => 'Neue Ordner erstellen',
    'Created' => 'Erstellt',
    'Default' => 'Standard',
    'Delete File' => 'Datei löschen',
    'Delete Folder' => 'Ordner löschen',
    'Delete files' => 'Dateien löschen',
    'Delete folders' => 'Ordner löschen',
    'Desktop' => 'Desktop',
    'Dimensions' => 'Dimensionen',
    'Edit File' => 'Datei bearbeiten',
    'Edit Folder' => 'Ordner bearbeiten',
    'File' => 'Datei',
    'Filename' => 'Dateiname',
    'Files' => 'Dateien',
    'Folder' => 'Ordner',
    'Folders' => 'Ordner',
    'Free' => 'Frei',
    'Height' => 'Höhe',
    'Image rotation' => 'Bilddrehung',
    'Import' => 'Importieren',
    'Import file from URL' => 'Datei von URL importieren',
    'Link' => 'Link',
    'Mobile' => 'Mobile',
    'New Folder' => 'Neuer Ordner',
    'Path' => 'Pfad',
    'Please type the folder name in the text field below to delete all related files. This cannot be undone, please be certain!' => 'Bitte gaben Sie den Ordnernamen an, um die Löschung des Ordners mit sämtlichen Dateien zu bestätigen. Bitte beachten Sie, dass eine Löschung unwiderruflich ist.',
    'Replace file' => 'Datei ersetzen',
    'Selection' => 'Selektion',
    'Show file' => 'Datei anzeigen',
    'Size' => 'Größe',
    'The file was created.' => 'Die Datei wurde erstellt.',
    'The file was deleted.' => 'Die Datei wurde gelöscht.',
    'The file was duplicated.' => 'Die Datei wurde dupliziert.',
    'The file was updated.' => 'Die Datei wurde aktualisiert.',
    'The folder was created.' => 'Der Ordner wurde erstellt.',
    'The folder was deleted.' => 'Der Ordner wurde gelöscht.',
    'The folder was updated.' => 'Der Ordner wurde aktualisiert.',
    'The transformation was deleted.' => 'Die Transformation wurde gelöscht.',
    'Transformation' => 'Transformation',
    'Transformations' => 'Transformationen',
    'Update files' => 'Dateien aktualisieren',
    'Update folders' => 'Order aktualisieren',
    'Upload Files' => 'Datei hochladen',
    'Upload or import new files' => 'Dateien hochladen oder importieren',
    'Width' => 'Breite',
];
