<?php

declare(strict_types=1);

namespace Hirtz\Media\Migrations;

use yii\db\Migration;

/**
 * The squashed schema of this bundle, generated by `bin/baseline` from a fully migrated database.
 *
 * A fresh install runs this and nothing before it. An upgraded project never runs it: the collapse
 * writes this class into `migration` instead, having deleted the v2 rows it replaces.
 *
 * Raw SQL rather than the schema builder, and deliberately: the point of generating from a grown
 * database is that the fresh schema is what an upgraded one has, and a rewrite through the builder is
 * a chance for the two to differ. Regenerate rather than edit.
 *
 * The foreign keys come after every table, because `product` and `product_variant` reference each
 * other and no single `CREATE TABLE` can say that.
 *
 * @noinspection PhpUnused
 */
class M260101000300MediaBaseline extends Migration
{
    public function safeUp(): void
    {
        $this->execute(<<<'SQL'
            CREATE TABLE `folder` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `position` int(11) unsigned NOT NULL DEFAULT 0,
              `name` varchar(250) NOT NULL,
              `path` varchar(250) NOT NULL,
              `file_count` int(11) NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `path` (`path`),
              KEY `folder_updated_by_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `file` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) unsigned NOT NULL DEFAULT 3,
              `folder_id` int(11) unsigned NOT NULL,
              `name` varchar(250) NOT NULL,
              `basename` varchar(250) NOT NULL,
              `extension` varchar(20) NOT NULL,
              `width` smallint(6) unsigned DEFAULT NULL,
              `height` smallint(6) unsigned DEFAULT NULL,
              `size` bigint(20) unsigned NOT NULL DEFAULT 0,
              `alt_text` varchar(250) DEFAULT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              `transformation_count` smallint(6) NOT NULL DEFAULT 0,
              `asset_count` smallint(6) NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `basename` (`basename`,`folder_id`,`extension`),
              KEY `folder_id` (`folder_id`),
              KEY `file_updated_by_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `asset` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `status` tinyint(1) unsigned NOT NULL DEFAULT 3,
              `type` smallint(6) NOT NULL DEFAULT 1,
              `model_class` varchar(255) NOT NULL,
              `model_id` bigint(20) unsigned NOT NULL,
              `file_id` int(11) unsigned NOT NULL,
              `custom_attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`custom_attributes`)),
              `position` int(11) unsigned NOT NULL DEFAULT 0,
              `updated_by_user_id` int(11) unsigned DEFAULT NULL,
              `updated_at` datetime DEFAULT NULL,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `model_file` (`model_class`,`model_id`,`file_id`),
              KEY `model_class` (`model_class`,`model_id`,`status`,`position`),
              KEY `file_id` (`file_id`),
              KEY `asset_updated_by_user_id_ibfk` (`updated_by_user_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            CREATE TABLE `file_transformation` (
              `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
              `file_id` int(11) unsigned NOT NULL,
              `name` varchar(50) NOT NULL,
              `extension` varchar(20) NOT NULL,
              `width` smallint(6) DEFAULT NULL,
              `height` smallint(6) DEFAULT NULL,
              `size` bigint(20) NOT NULL DEFAULT 0,
              `created_at` datetime NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `name` (`name`,`file_id`,`extension`),
              KEY `file_id` (`file_id`)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `folder` ADD CONSTRAINT `folder_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `file` ADD CONSTRAINT `file_folder_id_ibfk` FOREIGN KEY (`folder_id`) REFERENCES `folder` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `file` ADD CONSTRAINT `file_updated_by_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `asset` ADD CONSTRAINT `asset_file_id_ibfk` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `asset` ADD CONSTRAINT `asset_updated_by_user_id_ibfk` FOREIGN KEY (`updated_by_user_id`) REFERENCES `user` (`id`) ON DELETE SET NULL
            SQL);

        $this->execute(<<<'SQL'
            ALTER TABLE `file_transformation` ADD CONSTRAINT `transformation_file_id_ibfk` FOREIGN KEY (`file_id`) REFERENCES `file` (`id`) ON DELETE CASCADE
            SQL);

        $this->execute(<<<'SQL'
            INSERT INTO `auth_item` (`name`, `type`, `description`, `rule_name`, `data`, `updated_at`, `created_at`) VALUES
              ('file', '2', '{\"category\":\"media\",\"key\":\"AUTH_FILE_DESCRIPTION\"}', NULL, NULL, '1789985581', '1789985581'),
              ('folder', '2', '{\"category\":\"media\",\"key\":\"AUTH_FOLDER_DESCRIPTION\"}', NULL, NULL, '1789985581', '1789985581')
            SQL);

        $this->execute(<<<'SQL'
            INSERT INTO `auth_item_child` (`parent`, `child`) VALUES
              ('admin', 'file'),
              ('manager', 'file'),
              ('admin', 'folder'),
              ('manager', 'folder')
            SQL);
    }

    public function safeDown(): bool
    {
        echo "    > a baseline cannot be reverted, restore a dump instead\n";

        return false;
    }
}
