<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '16:9' => '',
    '180°' => '',
    '1:1' => '',
    '4:3' => '',
    '90° Clockwise' => '',
    '90° Counter Clockwise' => '',
    'A file with the name "{name}" already exists.' => '',
    'All devices' => '',
    'Alt text' => '',
    'Aspect ratio' => '',
    'Assets' => '',
    'Change folder order' => '',
    'Clear Selection' => '',
    'Create New Folder' => '',
    'Create new folders' => '',
    'Created' => '',
    'Default' => '',
    'Delete File' => '',
    'Delete Folder' => '',
    'Delete files' => '',
    'Delete folders' => '',
    'Desktop' => '',
    'Dimensions' => '',
    'Edit File' => '',
    'Edit Folder' => '',
    'File' => '',
    'Filename' => '',
    'Files' => '',
    'Folder' => '',
    'Folders' => '',
    'Free' => '',
    'Height' => '',
    'Image rotation' => '',
    'Import' => '',
    'Import file from URL' => '',
    'Link' => '',
    'Mobile' => '',
    'New Folder' => '',
    'Path' => '',
    'Please type the folder name in the text field below to delete all related files. This cannot be undone, please be certain!' => '',
    'Replace file' => '',
    'Selection' => '',
    'Show file' => '',
    'Size' => '',
    'The file was created.' => '',
    'The file was deleted.' => '',
    'The file was duplicated.' => '',
    'The file was updated.' => '',
    'The folder was created.' => '',
    'The folder was deleted.' => '',
    'The folder was updated.' => '',
    'The transformation was deleted.' => '',
    'Transformation' => '',
    'Transformations' => '',
    'Update files' => '',
    'Update folders' => '',
    'Upload Files' => '',
    'Upload or import new files' => '',
    'Width' => '',
];
